sudo: required


services:
  - docker

env:
  global:
    - PI_APP=youtube-proxy
  matrix:
    - PI_TYPE=rpi3

script: bash travis.sh || travis_terminate 1;


notifications:
   email:
      - mig.ruiz@gmail.com